### ISSUE TITLE
Trying to push my solutions in order to open a pr, but getting 403 permission denied. 

### ISSUE THREAD

**Issue by JakeDern** [mrcaron/SwInterns2018#1]
Commands used: 

`git branch -b <newbranch>`
`git add <filename>`
`git commit -m "Solutions to programming problems"`
`git push -u origin <newbranch> `

Any suggestions?

**Comment by mrcaron** [comment]
Right. You don't have permission to write to the repo. Make a pull request
instead. :)

**Comment by mrcaron** [comment]
I changed the wording. You have to fork this repo, then clone it to your desktop. :)
